# Generated by Django 4.2.7 on 2023-11-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mdeia/', verbose_name='Файл'),
        ),
    ]
